name: asn1lib
version: 1.6.5
description: An ASN1 parser library for Dart. Encodes / decodes from ASN1 Objects to BER bytes
homepage: https://github.com/wstrange/asn1lib
environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
# No dependencies!

dev_dependencies:
  collection: ^1.18.0
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.2

# PEM certs are for testing - and are OK to publish
false_secrets:
  - /test/resource/*.pem
  - test/*.dart
